### PR TITLE
Implement wamp components

### PR DESCRIPTION
**Pull request by davidchappelle**
This commit introduces the concept of components. A component
is simply a wrapper around a session object that provides
a number of conveniences. This eliminates a significant amount
of boilerplate code required to get a session established. In
addition, concrete component types have also been defined for
TCP and Unix Domain Sockets (UDS). Once this new API has been
accepted, documentation will follow accordingly.

Fixes: #53

### CODE REVIEW

**Comment by oberstet** [comment]
Interesting! So it hides some boilerplate, which is neat. The only thing: could we retain examples for both levels of use?

**Comment by oberstet** [comment]
@davidchappelle Another option would be to make the component interface the recommended API, and the current API an internal implementation detail. Having just one recommended API has something. Should we have two or one public API?

**Comment by davidchappelle** [comment]
@oberstet I think examples for both levels of use would be good. I was a bit uncertain on how best to proceed with the examples if we provided both ways without duplicating too much. If we simply preserved both sets of examples we could do:

    + examples
        + component
        + session

Thoughts? One might argue that the component API can be consulted as an example of how to use the portions of the session API that it utilizes internally.

We could hide session completely but that would leave the component API having to duplicate a large portion of the session interface. I am actually ok with taking a layered approach. It allows for lower level access where needed for higher level specialization. Some solid documentation and examples should make usage details fairly clear.

**Comment by oberstet** [comment]
> If we simply preserved both sets of examples we could do:

Yes, that would be fine I think! Just have two sets of example, even when that "duplicates" things. It's much easier to find the example of the right flavor then.

> Some solid documentation and examples 

Yeah, I think it would make sense to document and expose both methods, and gather some feedback with them.

**Comment by davidchappelle** [comment]
Should be good to merge now. I added some doxygen comments to the component classes and restored the original examples based on session.

**Comment by oberstet** [comment]
As commented on the other PR, we are currently incubating a new API in AB Py, which translated to C++ would work roughly like this.

A user creates a component by providing a (free standing) function like

```c++
boost::future<void> my_main_or_setup (boost::asio::io_service& loop,
                                      autobahn::wamp_session& session);
```

The boilerplate will then create a transport, a session config, a session, join the session and finally call above. Depending on component run mode ("main" or "setup"), the boilerplate will run above until end (the future fires) and then shut down ("main" mode) or run above and when it returns successfully, signal readiness of the component.

**Comment by davidchappelle** [comment]
Are we able to work with what I have for the time being? I would like to help drive your initiatives but due to approaching deadlines I don't have time to start re-architecting these types of things. What would be a happy compromise that can keep my moving forward on my objectives?

**Comment by oberstet** [comment]
@davidchappelle I do understand that you have a real project with deadlines. As do I;) Also, our focus right now is creating a long-term stable, cross-language API for WAMP. "cross-language" means as similar as possible. This will most likely look similar to what I posted above:

```c++
boost::future<void> my_main_or_setup (boost::asio::io_service& loop,
                                      autobahn::wamp_session& session);
```

> Are we able to work with what I have for the time being?

I would continue with what you have on your fork. I won't merge this PR, as it introduces new public API I don't agree with and it would be more work in the end ripping out stuff later again.

A general note: if you want to have big changes like this merged, it would be good to discuss important aspect before you start implementing. Because: now I have this big PR. You have spend time on it, and I am feeling bad rejecting it. We need more and better communication before starting coding ..

**Comment by davidchappelle** [comment]
I think what I will do for the time being is just pull the component code out and use it at the product level rather than in the library.

**Comment by oberstet** [comment]
yeah, makes sense. I think the most important interface is Session (the 4 core interactions). Any user code will use that a lot - so changes to that interface has massive consequences. All other API like how to actually create a Session has much less impact (but still).

**Pull request closed without merging**
