### PR TITLE
Changes required to get it built in MSVC 2013

### PR DESCRIPTION
**Pull request by IvaKom**

### CODE REVIEW

**Comment by oberstet** [comment]
@IvaKom thanks! have you tested it on clang and gcc?

**Comment by IvaKom** [comment]
I'll do.

**Comment by IvaKom** [comment]
I've found that I need to define MSGPACK_USE_LEGACY_NAME_AS_FLOAT on all platforms.
Compiled it with clang-3.5 / gcc-4.8, boost-1.57, msgpack-0.5.9.

**Comment by oberstet** [comment]
@IvaKom Thanks! Note https://github.com/tavendo/AutobahnCpp/commit/6de7bf09388279308196127ef120e7913761aeb5

**Comment by DZabavchik** [comment]
Just to cleanup the issues, this should be closed.

**Pull request merged**
