### PR TITLE
Abstract transports

### PR DESCRIPTION
**Pull request by davidchappelle**
As discussed in #54, this pull request takes a step in the right direction by adding an abstraction for session transports. I decided not to go for a full message based transport implementation at this time. Instead I took the first step forward which is to simply abstract out the transport and keep it stream based which is effectively what it was already being used as inside the session object. More details can be found in the commit message.

2 commits show up here. I am still trying to find the best workflow for working with github, branches, and pull requests. If you merge PR #55 first then you should be fine. Was trying to avoid piggy backing pull requests with multiple commits.

### CODE REVIEW

**Comment by oberstet** [comment]
@davidchappelle I think the right way to abstract WAMP transports is not abstracting streams, but message channels. Also, I'm not sure if Sessions should be templated with the Transport they use. Since that means, Sessions are tied to Transports: eg you can't have a Session not yet know via what Transport it'll connect. Both AB JS and Py are able to use "the first working transport" from a list of transports (fallbacks). Hence I think Transport (not streams, not message channels) could be provided to a Session using ITransport like pointers.

Rgd components: yes, I agree, reducing boilerplate is a goal. FWIW, we are currently incubating a newer API in AutobahnPython (eg https://github.com/tavendo/AutobahnPython/blob/master/examples/twisted/wamp/work/newapi/test_newapi12.py) with the stated goal of bringing Python and JS in Autobahn very close, and I think it would be possible with C++ too. Means: we are looking for an Autobahn API that looks very similar (as far as possible) across different languages.

In above Python example test_newapi12, you'll recognize the use of a functional/compositional style rather than inheritance. I could imagine a C++ API where the user simply provides a function roughly like `future<> my_main(_asio-loop_, Session)` and just uses the provided session. The new Py API currently being finalized. We will roll out the API to Py, then JS. And then I want to give C++ another iteration.

**Comment by davidchappelle** [comment]
@oberstet I think getting an abstraction in place for transports is the first step forward. Even with message channels you will need to abstract transports such that you can have message channel operate over different transports. i.e. TCP/UDS. So tackling transports first is a step forward in that direction.

I am sure that moving forward the API will continue to adapt which is to be expected. However, in the meantime the community needs to be able to use AutobahnCpp without waiting for longer term goals of the project. We are using it on a very large project and have deadlines to meet in 6 weeks time. This is why I am trying to make incremental improvements to the existing project. If the API changes date later date that is fine and we can work with that. In the meantime though we need to get it into a state where it can be used in our project.

**Comment by davidchappelle** [comment]
Getting rid of the template constraint on the session is actually a big help. For example, if you have 20, 30, 40, etc components and you want to deploy them in a flexible way, having the session depend on template parameters makes this very difficult. The project I am working on is quite large which is why I am running into these types of issues. There are many ways we can make this work for small examples where templates aren't a nuisance but in my case it becomes problematic.

**Comment by oberstet** [comment]
> Even with message channels you will need to abstract transports such that you can have message channel operate over different transports.

This "stream of bytes" abstraction already exists .. it's std streams, and concrete stream transports like boost::asio::ip::tcp::socket. IMO, there is no need to wrap this again.

I think the following would be a good approach:

1. remove the IStream/OStream template parameters from Session
2. create a WAMP message-based transport abstraction

> We are using it on a very large project and have deadlines to meet in 6 weeks time

I see. Our top focus is getting the API right. I suggest you move forward in your fork as you see fit for now, as I simply don't have time right now, and the API design takes time and iterations.

**Pull request closed without merging**
